### ISSUE TITLE
Cronjob ou Redis

### ISSUE THREAD

**Issue by blindibrasil** [lipecss/sendgrid-cronjob#2]
Olá,
Gostaria de debater um assunto com você sobre cronjobs.
Estou desenvolvendo uma aplicação e uma das funcionalidades é o envio programado de e-mail que pode funcionar de duas formas:
1 - Recorrente:
- Onde o usuário pode definir uma determinada data do mês e hora e na data escolhida de todos os meses este e-mail será enviado.

2 - Envio único: 
- O usuário programa apenas uma data e hora e neste momento será encaminhado o e-mail.

Acontece que começa a surgir alguns problemas que gostaria de saber como você acha ser a melhor forma para solucionar os casos abaixo:
1º - Como verificar no frontend os cronjobs ativos?
2º - Como cancelar um determinado cronjob programado errado?
3º - Servidor ficou offline. 
Como saber quais jobs não foram realizados? 
E como enviar eles para serem enviados novamente?
E ativar novamente os programados?
4º Será que fazer é melhor fazer essa programação de Jobs via Redis solicitando no Redis apenas que este determinado evento seja disparado no futuro?

Ficarei muito grato em saber suas respostas para estes assuntos.
Abraços.

**Comment by lipecss** [comment]
Olá, desculpa a demora, não tinha sido notificado. 

Você pode criar um micro serviço para os Jobs e a cada execução enviar para seu back um log do resultado. O Front pode se basear nessa APi que você criar e escutar o último status de cada Job.
Como sei usuário que irá criar essas terefas, o legal seria armazenar os Jobs em um banco e a cada x tempo antes de executar as tarefas seus sistema poderia verificar os Jobs ativos.
 No quesito de ficar offline o servidor, recomendo você fazer esse serviço a parte e sempre tratar a resposta do servidor.
